image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build
  - deploy

####################
### Docker Build ###
####################

build-titiler-docker:
  stage: build
  script:
    - docker info
    - docker login impactobservatory.azurecr.io -u $SP_APP_ID -p $SP_PASSWD
    - docker build -f Dockerfile.gunicorn -t impactobservatory.azurecr.io/titiler-pgstac:$CI_COMMIT_BRANCH.$CI_PIPELINE_ID .
    - docker push impactobservatory.azurecr.io/titiler-pgstac:$CI_COMMIT_BRANCH.$CI_PIPELINE_ID

#####################
### IO AKS Deploy ###
#####################

deploy-titiler-pgstac-webapp-dev:
  stage: deploy
  environment: io-dev
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context impactobservatory/titiler-pgstac:gitlab-agent-primary
    - kubectl get pods
    - sed -i "s/\$CI_COMMIT_BRANCH/$CI_COMMIT_BRANCH/g" titiler.yaml
    - sed -i "s/\$CI_PIPELINE_ID/$CI_PIPELINE_ID/g" titiler.yaml
    - sed -i "s/\$NAMESPACE/$NAMESPACE/g" titiler.yaml
    - sed -i "s/\$REPLICA_COUNT/$REPLICA_COUNT/g" titiler.yaml
    - sed -i "s/\$DNS_A_RECORD/$DNS_A_RECORD/g" titiler.yaml
    - sed -i "s/\$STORAGE_ACCOUNT_KEY/$STORAGE_ACCOUNT_KEY/g" titiler.yaml
    - sed -i "s/\$DOCKER_REGISTRY_SERVER_PASSWORD/$DOCKER_REGISTRY_SERVER_PASSWORD/g" titiler.yaml
    - sed -i "s/\$POSTGRES_PASS/$POSTGRES_PASS/g" titiler.yaml
    - kubectl apply -f ./titiler.yaml

deploy-titiler-pgstac-webapp-prod:
  stage: deploy
  environment: io-prod
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context impactobservatory/titiler-pgstac:gitlab-agent-primary
    - kubectl get pods
    - sed -i "s/\$CI_COMMIT_BRANCH/$CI_COMMIT_BRANCH/g" titiler.yaml
    - sed -i "s/\$CI_PIPELINE_ID/$CI_PIPELINE_ID/g" titiler.yaml
    - sed -i "s/\$NAMESPACE/$NAMESPACE/g" titiler.yaml
    - sed -i "s/\$REPLICA_COUNT/$REPLICA_COUNT/g" titiler.yaml
    - sed -i "s/\$DNS_A_RECORD/$DNS_A_RECORD/g" titiler.yaml
    - sed -i "s/\$STORAGE_ACCOUNT_KEY/$STORAGE_ACCOUNT_KEY/g" titiler.yaml
    - sed -i "s/\$DOCKER_REGISTRY_SERVER_PASSWORD/$DOCKER_REGISTRY_SERVER_PASSWORD/g" titiler.yaml
    - sed -i "s/\$POSTGRES_PASS/$POSTGRES_PASS/g" titiler.yaml
    - kubectl apply -f ./titiler.yaml
  needs: ["deploy-titiler-pgstac-webapp-dev"]
  when: manual

################################
### UNBL Function App Deploy ###
################################

deploy-titiler-pgstac-webapp-unbl-staging:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:latest
  script:
    - az login --service-principal -u $SP_APP_ID -p $SP_PASSWD --tenant $AZURE_TENANT_ID
    - az webapp config container set --name io-tiler-navigator 
      --resource-group io-tiler-navigator-resource-group 
      --docker-custom-image-name impactobservatory.azurecr.io/titiler-pgstac:$CI_COMMIT_BRANCH.$CI_PIPELINE_ID 
      --docker-registry-server-url https://impactobservatory.azurecr.io 
      --slot unbl-staging
  when: manual
  
deploy-titiler-pgstac-webapp-unbl:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:latest
  script:
    - az login --service-principal -u $SP_APP_ID -p $SP_PASSWD --tenant $AZURE_TENANT_ID
    - az webapp config container set --name io-tiler-navigator 
      --resource-group io-tiler-navigator-resource-group 
      --docker-custom-image-name impactobservatory.azurecr.io/titiler-pgstac:$CI_COMMIT_BRANCH.$CI_PIPELINE_ID 
      --docker-registry-server-url https://impactobservatory.azurecr.io 
      --slot unbl
  when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "master"