site_name: TiTiler.PgSTAC
site_description: Dynamic Mosaics From PgSTAC database.

docs_dir: 'src'
site_dir: 'build'

repo_name: "stac-utils/titiler-pgstac"
repo_url: "https://github.com/stac-utils/titiler-pgstac"
edit_uri: "blob/master/docs/"
site_url: "https://stac-utils.github.io/titiler-pgstac/"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/stac-utils"

nav:
  - Home: "index.md"
  - Intro: "intro.md"
  - Endpoints:
    - Mosaic: "mosaic_endpoints.md"
    - Item: "item_endpoints.md"
    - TileMatrixSet: "tms_endpoints.md"
  - Tiler Factories: "tiler_factories.md"
  - Advanced usage:
    - Mosaic metadata specification: "advanced/metadata.md"
    - Mosaic list: "advanced/mosaic_list.md"
    - Custom search model: "advanced/custom_search.md"
    - Custom TileJSON endpoint : "advanced/custom_tilejson.md"
    - Custom feature crop endpoint: "advanced/geojson_crop.md"
  - Examples:
    - demo: "notebooks/demo.ipynb"
  - Development - Contributing: "contributing.md"
  - Release notes: "release-notes.md"

plugins:
  - search
  - mkdocs-jupyter:
      include_source: True

theme:
  name: material


# https://github.com/kylebarron/cogeo-mosaic/blob/mkdocs/mkdocs.yml#L50-L75
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret:
      insert: false
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
